# gcloud goal variable - single file pattern

homebrew_cask_apps:
- google-cloud-sdk # Set of tools to manage resources and applications hosted on Google Cloud. https://cloud.google.com/sdk/

gcloud_components:
- beta
- gke-gcloud-auth-plugin
