# gcloud goal variable - single file pattern

homebrew_taps: []

homebrew_cask_apps:
- google-cloud-sdk # Set of tools to manage resources and applications hosted on Google Cloud. https://cloud.google.com/sdk/

homebrew_cask_accept_external_apps: true

gcloud_components:
- beta
- gke-gcloud-auth-plugin
