---
homebrew_cask_appdir: /Applications

homebrew_cask_apps:
- 1password # Password manager, https://1password.com/
- 1password-cli # Command-line interface for 1Password. https://1password.com/
- obsidian # A second brain, for you, forever. https://obsidian.md/
- logseq # A privacy-first, open-source platform for knowledge sharing and management. https://logseq.com/
- notion # All-in-one workspace. https://www.notion.so/
- ticktick # To-do list and task manager. https://ticktick.com/
- maccy # Clipboard manager, https://github.com/p0deje/Maccy
- rectangle # Move and resize windows on macOS with keyboard shortcuts and snap areas, https://github.com/rxhanson/Rectangle
- drawio # Draw diagrams free. https://www.diagrams.net/
- go2shell # Opens a terminal window to the current directory in Finder. https://zipzapmac.com/go2shell
- keka # File archiver for macOS. https://www.keka.io/
- obs # Free and open-source software for screen recording and live streaming. https://obsproject.com/
- postman # API development environment. https://www.postman.com/
- insomnia # Cross-platform REST client. https://insomnia.rest/
- vlc # Open-source multimedia player. https://www.videolan.org/vlc/
- vnc-viewer # Remote desktop software. https://www.realvnc.com/en/connect/download/viewer/
- shottr # Screenshot tool for macOS. https://shottr.cc/
- cursor # Write, edit, and chat about your code with AI. https://www.cursor.com/

homebrew_cask_uninstalled_apps: []
